// index..js
module.exports = {
  app: {
    port: process.env.PORT || 1575,
    appName: process.env.APP_NAME || "dashboard",
    env: process.env.NODE_ENV || "development",
    isProd: process.env.NODE_ENV === "prod",
    getAdminFolderName: process.env.ADMIN_FOLDER_NAME || "admin",
    getApiFolderName: process.env.API_FOLDER_NAME || "api",
  },
  db: {
    port: process.env.DB_PORT || 27117,
    database: process.env.DB_DATABASE || "adreeDb",
    password: process.env.DB_PASSWORD || "7fyk6NyMf7yiDhLA",
    username: process.env.DB_USERNAME || "adree",
    host: process.env.DB_HOST || "104.211.217.29",
    dialect: "mongodb",
  },
  winiston: {
    logpath: "/iLrnLogs/logs/",
  },
  auth: {
    jwtSecret: process.env.JWT_SECRET || "MyS3cr3tK3Y",
    jwt_expiresin: process.env.JWT_EXPIRES_IN || "1d",
    saltRounds: process.env.SALT_ROUND || 10,
    jwtSession: { session: false },
    refresh_token_secret:
      process.env.REFRESH_TOKEN_SECRET || "VmVyeVBvd2VyZnVsbFNlY3JldA==",
    refresh_token_expiresin: process.env.REFRESH_TOKEN_EXPIRES_IN || "2d", // 2 days
  },
  other: {
    pageLimit: 10,
    clubArr: [
      "dr",
      "3w",
      "4w",
      "5w",
      "7w",
      "2h",
      "3h",
      "4h",
      "5h",
      "6h",
      "1i",
      "2i",
      "3i",
      "4i",
      "5i",
      "6i",
      "7i",
      "8i",
      "9i",
      "pw",
      "sw",
      "gw",
      "lw",
      "50w",
      "52w",
      "54w",
      "56w",
      "58w",
      "60w",
      "62w",
      "64w",
    ],
  },
};
